[package]
name = "async_stdcode"
version = "1.0.0"
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
futures-util = {version="0.3.31", features=["io"]}
stdcode = "0.1.14"
bincode="1"
serde = "1.0.219"

[dev-dependencies]
pollster = "0.4.0"
bipe = "0.2.8"
